import { GetStaticProps, GetStaticPropsResult } from "next";

import FrontLayout from "@/layout/front/front";
import Head from "next/head";
import { PortableText } from "@portabletext/react";
import { PostListBox } from "@/components/post-list/postList";
import { Section } from "@/components/section/section";
import { client } from "@/sanity/client";
import styles from "@/styles/frontPage.module.css";

interface IPage {
  _id: string;
  body: any[];
  title: string;
}
interface IPost {
  _id: string;
  author: { name: string };
  categories: { slug: { _type: string; current: string }; title: string }[];
  mainImage: { _type: string; asset: { _ref: string; _type: string } };
  slug: { _type: string; current: string };
  title: string;
}
interface HomeProps {
  page: IPage;
  posts: IPost[];
}
export default function Home({ page, posts }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FrontLayout>
        <main>
          <section className={styles.wrapper}>
            <video width="100%" autoPlay muted loop id="myVideo">
              <source src="/Do-you-hear-slutt.mp4" type="video/mp4" />
              Your browser does not support HTML5 video.
            </video>
            <h1
              className={
                styles.videoSectionCenter + " " + styles.videoSectionCenterTitle
              }
            >
              Glommasvingen Janitsjar
            </h1>
            <h2
              className={
                styles.videoSectionCenter +
                " " +
                styles.videoSectionCenterSubTitle
              }
            >
              Det lokale korpset for Kongsvinger og Sør-Odal
            </h2>
          </section>
          <div className={styles.page}>
            <Section>
              <article>
                <PortableText value={page.body} />
              </article>
            </Section>
            <Section>
              {posts.map((post) => (
                <PostListBox
                  key={post._id}
                  title={post.title}
                  image={post.mainImage}
                  author={post.author.name}
                />
              ))}
            </Section>
          </div>
        </main>
      </FrontLayout>
    </>
  );
}

export const getStaticProps: GetStaticProps<HomeProps, {}> = async (
  context
) => {
  const page = await client.fetch(`*[_type == "page"][0] {_id, body, title}`);
  const posts = await client.fetch(
    `*[_type == "post"] {_id, author->{name}, categories[]->{title, slug},mainImage, slug, title, publishedAt } | order(publishedAt desc)`
  );

  return {
    props: {
      page,
      posts,
    },
  };
};
